edition = "2024"

max_width = 130
tab_spaces = 4
hard_tabs = false
use_small_heuristics = "Max"

imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
merge_derives = true
use_field_init_shorthand = true
reorder_impl_items = true

newline_style = "Unix"
trailing_comma = "Vertical"
match_block_trailing_comma = true

format_code_in_doc_comments = true
normalize_doc_attributes = true
wrap_comments = true
